# -*- coding: utf-8 -*-
"""Project2_Data_Classification_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOzZDJu-f8eH273opZwhZ-VbbRwfo2hM
"""

print("Welcome to Project 2")
print("Data Classification Using AI")

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()

print(iris)

print(iris.target_names)

print(iris.feature_names)

print(iris.data[0])

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Predicted Classes:", y_pred)
print("Actual Classes:", y_test)

print("\n===== PROJECT COMPLETED =====")
print("Project Name : Data Classification AI")
print("Dataset      : Iris Dataset")
print("Algorithm    : Decision Tree Classifier")
print(f"Accuracy     : {accuracy*100:.2f}%")
print("Status       : Successfully Completed")